D = 15
OUT = 4

ARCHITECTURES = {
    "Boubekki":(
        [('input',D),
            ('dense', (500, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (500, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (2000, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
        ],[('input' , OUT),
            ('dense', (2000, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (500, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (500, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
        ]
        ),
    "Wendler":(
        [('input',D),
            ('dense', (100, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
        ],[('input' , OUT),
            ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (100, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
        ]
    ),
    "10z":(
        [('input',D),
            ('dense', (100, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (10, 'glorot_uniform', 'glorot_normal') ),
        ],[('input' , 10),
            ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (100, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
        ]
    ),
    "SmallLayers":(
        [('input',D),
            ('dense', (50, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
        ],[('input' , OUT),
            ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (50, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
        ]
    ),
    "ExtraLayer":(
        [('input',D),
          ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (100, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
        ],[('input' , OUT),
            ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (100, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
        ]
    ),
    "SmallExtraLayer":(
        [('input',D),
          ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (50, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
        ],[('input' , OUT),
            ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (50, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
        ]
    ),
    "OneIntLayer50":(
        [('input',D),
            ('dense', (50, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
        ],[('input' , OUT),
            ('dense', (50, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
        ]
    ),
    "OneIntLayer20":(
        [('input',D),
            ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
        ],[('input' , OUT),
            ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
        ]
    ),
}